version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run:
          name: Install Poetry
          command: pip install poetry

      - run:
          name: Install Dependencies
          command: poetry install

      - run:
          name: Lint
          command: poetry run flake8

  integration_test:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout

      - run:
          name: Run local Autograh
          command: docker run --detach --name autograph-server mozilla/autograph

      - run:
          name: Run local Kinto
          command: |
            mkdir --mode=777 attachments && \
            docker run --name kinto.local \
                       --detach \
                       -v `pwd`/settings.ini:/etc/kinto.ini \
                       -v `pwd`/attachments:/tmp/attachments \
                       -e KINTO_INI=/etc/kinto.ini \
                       -p 8888:8888 \
                       --link autograph-server:autograph-server \
                       mozilla/kinto-dist && \
            curl --retry 10 --retry-delay 1 --retry-connrefused http://0.0.0.0:8888/v1/

      - run:
          name: Build test container image
          command: docker build -t app:build .

      - run:
          name: Test against local server
          command: |
            docker run --link kinto.local:kinto.local \
                       --env TEST_TYPE=dist \
                       --env TEST_ENV=local \
                       app:build

workflows:
  version: 2
  main:
    jobs:
      - lint
      - integration_test
